name: cipher
version: 0.7.0
author: Iván Zaera Avellón <izaera@gmail.com>
description: A Dart library implementing cryptographic algorithms.
homepage: http://izaera.github.io/cipher/
environment:
  sdk: '>=0.8.10+6 <2.0.0'
documentation: http://izaera.github.io/cipher/api/
dependencies:
  bignum: '>=0.0.5 <0.1.0'
  fixnum: '>=0.9.0 <0.10.0'
dev_dependencies:
  benchmark_harness: '>=1.0.4 <2.0.0'
  browser: '>=0.9.0 <0.10.0'
  unittest: '>=0.9.0 <0.10.0'
